apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: django
          image: shaggydog/gamedb:latest
          imagePullPolicy: Always
          command: ["./manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: gamedb-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: gamedb-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gamedb-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: gamedb-secrets
                  key: POSTGRES_PORT
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gamedb-secrets
                  key: SECRET_KEY