apiVersion: app/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  selector:
    matchLables:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: django
          image: shaggydog/gamedb-web
          ports: 8000