# Generated by Django 3.1.1 on 2020-09-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fo76', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stash',
            name='item',
        ),
        migrations.AddField(
            model_name='items',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='stash',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Stash',
        ),
    ]
